apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mern-app
spec:
  # ClusterIP — database must never be reachable outside the cluster
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
