apiVersion: v1
kind: Secret
metadata:
  name: server-secrets
  namespace: mern-app
type: Opaque
stringData:
  ATLAS_URI: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/sample_training?authSource=admin"
